In [3]:
import numpy as np

my_List = [1,2,3]
arr = np.array(my_List)

my_mat = [[1,2,3], [2,3,4], [3,4,5]]

arr2 = np.array(my_mat)

#like python's range (start,end,step size)
np.arange(0,10,2)

np.zeros((3,3))
np.ones((3,3))

# start, stop, number for evenly spaced points between start and stop
np.linspace(0,5,10)

#creates an identity matrix
np.eye(4)

#random numbers from 0 to 1, dimensions inside brackets
np.random.rand(5,5)
np.random.rand(2,4)

#between -1 and 1
np.random.randn(5,5)

#random integers from low to high number, 3rd argument is how many numbers
arr = np.random.randint(1, 100, 10)

#reshapes arrays, depends on size of array
arr.reshape(2,5)


arr.max()
arr.min()

#index of max/min
arr.argmax()
arr.argmin()

#gives the dimensions of array
arr.shape 

#array datatype
arr.dtype




array([[0.73853651, 0.88831447, 0.85442684, 0.25316726],
       [0.09656985, 0.68948639, 0.7340969 , 0.95857592]])

In [46]:
arr = np.arange(0,11)

#slicing
arr[0:4]
arr[5:]

arr[0:5] = 100


arr = np.arange(0,11)

slice_of_arr = arr[0:6]

#also occurs in original array does not create a copy
slice_of_arr[:] = 99

#to create a copy of array
arr_copy = arr.copy()
arr_copy[:] = 100



[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99 99 99  6  7  8  9 10]


In [52]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

#arr[2][1] = arr[2,1]
arr_2d[1,2]

#2d slicing
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [64]:
arr = np.arange(1,11)

#gives a boolean array
bool_array = arr > 5

#only returns elements which are true
arr[bool_array]

#above in one step
arr[arr>5]

arr = np.arange(50).reshape(5,10)

arr[1:3,3:5]



array([[13, 14],
       [23, 24]])

In [78]:
arr = np.arange(0,11)

arr + arr
arr * arr
arr - 100
#1/arr
arr ** 10

#check numpy math functions in docs
np.sqrt(arr)
np.exp(arr)
np.max(arr) #arr.max()

#np.log(arr)
np.sin(arr)



array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])